INSERT INTO hotel (name, description, facility, location, img) VALUES
('Hotel Kathmandu Palace', 'A luxury hotel in the heart of Kathmandu.', 'Free WiFi, Spa, Pool, Restaurant', 'Kathmandu, Thamel', 'ktm_palace.jpg'),
('Mountain View Resort', 'Resort with stunning views of the Himalayas.', 'Free WiFi, Guided Tours, Restaurant', 'Kathmandu, Boudha', 'mountain_view.jpg'),
('Everest Guest House', 'Comfortable guest house with budget-friendly rooms.', 'Free WiFi, Airport Shuttle, Restaurant', 'Kathmandu, Lazimpat', 'everest_guest_house.jpg'),
('Heritage Hotel', 'Experience the rich culture of Kathmandu at this heritage property.', 'Free WiFi, Cultural Tours, Restaurant', 'Kathmandu, Patan', 'heritage_hotel.jpg'),
('Valley Inn', 'A cozy inn located near the city center.', 'Free WiFi, Room Service, Restaurant', 'Kathmandu, New Road', 'valley_inn.jpg'),
('City Center Hotel', 'Modern hotel with easy access to shopping and attractions.', 'Free WiFi, Gym, Restaurant', 'Kathmandu, Durbar Marg', 'city_center.jpg'),
('Temple View Lodge', 'Lodge with a view of Pashupatinath Temple.', 'Free WiFi, Room Service, Restaurant', 'Kathmandu, Gaushala', 'temple_view.jpg'),
('Kathmandu Suites', 'Spacious suites with modern amenities.', 'Free WiFi, Spa, Restaurant', 'Kathmandu, Lazimpat', 'kathmandu_suites.jpg'),
('Peaceful Resort', 'A tranquil resort on the outskirts of the city.', 'Free WiFi, Garden, Restaurant', 'Kathmandu, Budhanilkantha', 'peaceful_resort.jpg'),
('Boutique Hotel Himalaya', 'A boutique hotel with a unique Himalayan touch.', 'Free WiFi, Spa, Restaurant', 'Kathmandu, Jawalakhel', 'boutique_himalaya.jpg'),
('Sunrise Hotel', 'Hotel with a beautiful view of the sunrise over the mountains.', 'Free WiFi, Airport Shuttle, Restaurant', 'Kathmandu, Swayambhu', 'sunrise_hotel.jpg'),
('Kathmandu Plaza', 'Centrally located hotel with modern facilities.', 'Free WiFi, Conference Room, Restaurant', 'Kathmandu, Baneshwor', 'kathmandu_plaza.jpg'),
('Royal Garden Hotel', 'Luxurious hotel with a royal touch.', 'Free WiFi, Spa, Restaurant', 'Kathmandu, Lazimpat', 'royal_garden.jpg'),
('Natures Retreat', 'A retreat surrounded by nature in the hills.', 'Free WiFi, Yoga Classes, Restaurant', 'Kathmandu, Pharping', 'natures_retreat.jpg'),
('Thamel Eco Resort', 'Eco-friendly resort in the bustling Thamel area.', 'Free WiFi, Eco-Tours, Restaurant', 'Kathmandu, Thamel', 'thamel_eco.jpg'),
('Golden Temple Inn', 'Hotel near the famous Golden Temple.', 'Free WiFi, Cultural Tours, Restaurant', 'Kathmandu, Patan', 'golden_temple.jpg'),
('Cityscape Hotel', 'Hotel with a panoramic view of the Kathmandu skyline.', 'Free WiFi, Rooftop Bar, Restaurant', 'Kathmandu, Boudha', 'cityscape_hotel.jpg'),
('Tranquil Valley Hotel', 'A quiet retreat in a bustling city.', 'Free WiFi, Meditation Center, Restaurant', 'Kathmandu, Kapan', 'tranquil_valley.jpg'),
('Kathmandu View Tower Hotel', 'Hotel with stunning views of the entire Kathmandu valley.', 'Free WiFi, Observation Deck, Restaurant', 'Kathmandu, Kalanki', 'ktm_view_tower.jpg'),
('Everest Base Hotel', 'Hotel offering base camp-style accommodation in the city.', 'Free WiFi, Adventure Tours, Restaurant', 'Kathmandu, Balaju', 'everest_base.jpg');
